<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class ImportStudents extends Command
{
    protected $signature = 'import:students';
    protected $description = 'Import students from Flask database';

    public function handle()
    {
        try {
            // Truncate the student table to avoid conflicts
            DB::statement('SET FOREIGN_KEY_CHECKS=0;');
            DB::table('students')->truncate();
            DB::statement('SET FOREIGN_KEY_CHECKS=1;');
            $this->info('Truncated students table');
            Log::info('Truncated students table');

            // Student data
            $students = [
                ['id' => 7, 'first_name' => 'Ogochukwu', 'last_name' => 'Okorie', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 20:27:38', 'approved' => 1, 'user_id' => 9, 'middle_name' => 'Obioma', 'parent_name' => '', 'reg_no' => 'AAIS/0559/007', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 8, 'first_name' => 'David', 'last_name' => 'Ndubueze', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 20:28:13', 'approved' => 1, 'user_id' => 10, 'middle_name' => 'Chidiebube', 'parent_name' => '', 'reg_no' => 'AAIS/0559/008', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 9, 'first_name' => 'Taylor', 'last_name' => 'Imeole', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 20:29:14', 'approved' => 1, 'user_id' => 11, 'middle_name' => 'Ayor', 'parent_name' => '', 'reg_no' => 'AAIS/0559/009', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 10, 'first_name' => 'Temple', 'last_name' => 'Williams', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 20:30:56', 'approved' => 1, 'user_id' => 12, 'middle_name' => 'Akachukwu', 'parent_name' => '', 'reg_no' => 'AAIS/0559/010', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 11, 'first_name' => 'Jadon', 'last_name' => 'Nwoji', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 20:32:07', 'approved' => 1, 'user_id' => 13, 'middle_name' => 'Chukwudi', 'parent_name' => '', 'reg_no' => 'AAIS/0559/011', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 12, 'first_name' => 'Joshua', 'last_name' => 'Nwoji', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 20:32:59', 'approved' => 1, 'user_id' => 14, 'middle_name' => 'Chimeremeze', 'parent_name' => '', 'reg_no' => 'AAIS/0559/012', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 13, 'first_name' => 'Ezinne', 'last_name' => 'Chinenye', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 20:33:45', 'approved' => 1, 'user_id' => 15, 'middle_name' => 'Esther', 'parent_name' => '', 'reg_no' => 'AAIS/0559/013', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 14, 'first_name' => 'John', 'last_name' => 'Miracle', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 20:34:16', 'approved' => 1, 'user_id' => 16, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/014', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 15, 'first_name' => 'Adaeze', 'last_name' => 'Okechukwu', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 20:35:04', 'approved' => 1, 'user_id' => 17, 'middle_name' => 'Nnennaya', 'parent_name' => '', 'reg_no' => 'AAIS/0559/015', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 16, 'first_name' => 'Ikechukwu', 'last_name' => 'Chukwubuikem', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 20:35:56', 'approved' => 1, 'user_id' => 18, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/016', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 17, 'first_name' => 'Goodluck', 'last_name' => 'Nwankpa', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 20:50:18', 'approved' => 1, 'user_id' => 19, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/017', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 18, 'first_name' => 'Wisdom', 'last_name' => 'Ndubueze', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 20:51:00', 'approved' => 1, 'user_id' => 20, 'middle_name' => 'Chijindu', 'parent_name' => '', 'reg_no' => 'AAIS/0559/018', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 19, 'first_name' => 'Wisdom', 'last_name' => 'Chinyeaka', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 20:51:43', 'approved' => 1, 'user_id' => 21, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/019', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 20, 'first_name' => 'Oluchukwu', 'last_name' => 'Chinedu', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 20:52:53', 'approved' => 1, 'user_id' => 22, 'middle_name' => 'Jessica', 'parent_name' => '', 'reg_no' => 'AAIS/0559/020', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 21, 'first_name' => 'Miracle', 'last_name' => 'Ezereibe', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 20:54:43', 'approved' => 1, 'user_id' => 23, 'middle_name' => 'Chidera', 'parent_name' => '', 'reg_no' => 'AAIS/0559/021', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 22, 'first_name' => 'Ifunanya', 'last_name' => 'Charles', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 20:56:02', 'approved' => 1, 'user_id' => 24, 'middle_name' => 'Exceedinggrace', 'parent_name' => '', 'reg_no' => 'AAIS/0559/022', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 23, 'first_name' => 'Elder', 'last_name' => 'Udochukwu', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 20:56:41', 'approved' => 1, 'user_id' => 25, 'middle_name' => 'Udochukwu', 'parent_name' => '', 'reg_no' => 'AAIS/0559/023', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 24, 'first_name' => 'Special', 'last_name' => 'Chidi', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 20:57:09', 'approved' => 1, 'user_id' => 26, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/024', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 25, 'first_name' => 'Ijeoma', 'last_name' => 'Moses', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 20:57:48', 'approved' => 1, 'user_id' => 27, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/025', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 26, 'first_name' => 'Genevieve', 'last_name' => 'Joseph', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 20:58:15', 'approved' => 1, 'user_id' => 28, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/026', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 27, 'first_name' => 'David', 'last_name' => 'Asoegwu', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 20:58:42', 'approved' => 1, 'user_id' => 29, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/027', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 28, 'first_name' => 'DivineFavour', 'last_name' => 'Israel', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 21:01:52', 'approved' => 1, 'user_id' => 30, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/028', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 29, 'first_name' => 'Emmanuel', 'last_name' => 'Divine', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 21:02:41', 'approved' => 1, 'user_id' => 31, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/029', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 30, 'first_name' => 'MaryJane', 'last_name' => 'Joseph', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 21:04:21', 'approved' => 1, 'user_id' => 32, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/030', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 31, 'first_name' => 'Gift', 'last_name' => 'John', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 21:04:55', 'approved' => 1, 'user_id' => 33, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/031', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 32, 'first_name' => 'Excel', 'last_name' => 'Maduabuchi', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 21:12:13', 'approved' => 1, 'user_id' => 34, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/032', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 33, 'first_name' => 'Prince', 'last_name' => 'Tochukwu', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 21:13:18', 'approved' => 1, 'user_id' => 35, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/033', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 34, 'first_name' => 'Mary', 'last_name' => 'John', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 21:14:13', 'approved' => 1, 'user_id' => 36, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/034', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 35, 'first_name' => 'Great', 'last_name' => 'Chinyeaka', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 21:16:23', 'approved' => 1, 'user_id' => 37, 'middle_name' => 'Chibuikem', 'parent_name' => '', 'reg_no' => 'AAIS/0559/035', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 36, 'first_name' => 'Adaeze', 'last_name' => 'Moses', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 21:17:23', 'approved' => 1, 'user_id' => 38, 'middle_name' => 'Benedita', 'parent_name' => '', 'reg_no' => 'AAIS/0559/036', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 37, 'first_name' => 'Amarachi', 'last_name' => 'Chinedu', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 21:18:57', 'approved' => 1, 'user_id' => 39, 'middle_name' => 'Mary', 'parent_name' => '', 'reg_no' => 'AAIS/0559/037', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 38, 'first_name' => 'Nneomannaya', 'last_name' => 'Nwankpa', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 21:20:16', 'approved' => 1, 'user_id' => 40, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/038', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 39, 'first_name' => 'Ugoeze', 'last_name' => 'Chidi', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 21:21:03', 'approved' => 1, 'user_id' => 41, 'middle_name' => 'Delight', 'parent_name' => '', 'reg_no' => 'AAIS/0559/039', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 40, 'first_name' => 'Chikamso', 'last_name' => 'Odimegwu', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 21:22:43', 'approved' => 1, 'user_id' => 42, 'middle_name' => 'Daniel', 'parent_name' => '', 'reg_no' => 'AAIS/0559/040', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 41, 'first_name' => 'Divine', 'last_name' => 'Ndubueze', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-18 21:23:44', 'approved' => 1, 'user_id' => 43, 'middle_name' => 'Chinaecherem', 'parent_name' => '', 'reg_no' => 'AAIS/0559/041', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 42, 'first_name' => 'Future', 'last_name' => 'Anosike', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 00:47:30', 'approved' => 1, 'user_id' => 44, 'middle_name' => 'Junior', 'parent_name' => '', 'reg_no' => 'AAIS/0559/042', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 43, 'first_name' => 'Daniel', 'last_name' => 'Asoegwu', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 00:48:02', 'approved' => 1, 'user_id' => 45, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/043', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 44, 'first_name' => 'Flourish', 'last_name' => 'Maduabuchi', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 00:48:53', 'approved' => 1, 'user_id' => 46, 'middle_name' => 'Chimamanda', 'parent_name' => '', 'reg_no' => 'AAIS/0559/044', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 46, 'first_name' => 'Nice', 'last_name' => 'Freedom', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 00:50:41', 'approved' => 1, 'user_id' => 48, 'middle_name' => 'Chibuikem', 'parent_name' => '', 'reg_no' => 'AAIS/0559/046', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 47, 'first_name' => 'David', 'last_name' => 'Chinenye', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 00:51:55', 'approved' => 1, 'user_id' => 49, 'middle_name' => 'Chimnadinda', 'parent_name' => '', 'reg_no' => 'AAIS/0559/047', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 48, 'first_name' => 'Victory', 'last_name' => 'Gideon', 'gender' => 'Male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 00:55:27', 'approved' => 1, 'user_id' => 50, 'middle_name' => 'Chibuikem', 'parent_name' => '', 'reg_no' => 'AAIS/0559/048', 'profile_pic' => '/static/images/uploads/profile_pics/48_school_logo_3.jpg', 'parent_phone_number' => NULL],
                ['id' => 49, 'first_name' => 'Callistus', 'last_name' => 'Moses', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 00:56:13', 'approved' => 1, 'user_id' => 51, 'middle_name' => 'Ekeoma', 'parent_name' => '', 'reg_no' => 'AAIS/0559/049', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 50, 'first_name' => 'Samuel', 'last_name' => 'Ime', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 00:56:40', 'approved' => 1, 'user_id' => 52, 'middle_name' => 'Chidiebere', 'parent_name' => '', 'reg_no' => 'AAIS/0559/050', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 51, 'first_name' => 'Winner', 'last_name' => 'Chidi', 'gender' => 'male', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 00:58:08', 'approved' => 1, 'user_id' => 53, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/051', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 52, 'first_name' => 'Miracle', 'last_name' => 'Ndubueze', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 00:59:01', 'approved' => 1, 'user_id' => 54, 'middle_name' => 'Chizimdiri', 'parent_name' => '', 'reg_no' => 'AAIS/0559/052', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 53, 'first_name' => 'Esther', 'last_name' => 'Nwankpa', 'gender' => 'female', 'date_of_birth' => '2024-06-18', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 00:59:55', 'approved' => 1, 'user_id' => 55, 'middle_name' => 'Chiwenmeri', 'parent_name' => '', 'reg_no' => 'AAIS/0559/053', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 54, 'first_name' => 'Chizaram', 'last_name' => 'Prince', 'gender' => 'male', 'date_of_birth' => '2024-06-19', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 01:00:35', 'approved' => 1, 'user_id' => 56, 'middle_name' => 'Chizaram', 'parent_name' => '', 'reg_no' => 'AAIS/0559/054', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 55, 'first_name' => 'Chinyere', 'last_name' => 'Emmanuel', 'gender' => 'female', 'date_of_birth' => '2024-06-19', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 01:01:55', 'approved' => 1, 'user_id' => 57, 'middle_name' => 'Precious', 'parent_name' => '', 'reg_no' => 'AAIS/0559/055', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 56, 'first_name' => 'Marvellous', 'last_name' => 'Maduabuchi', 'gender' => 'male', 'date_of_birth' => '2024-06-19', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 01:02:37', 'approved' => 1, 'user_id' => 58, 'middle_name' => 'Kamsi', 'parent_name' => '', 'reg_no' => 'AAIS/0559/056', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 57, 'first_name' => 'Treasure', 'last_name' => 'Chidi', 'gender' => 'female', 'date_of_birth' => '2024-06-19', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 01:03:37', 'approved' => 1, 'user_id' => 59, 'middle_name' => 'Chinaecherem', 'parent_name' => '', 'reg_no' => 'AAIS/0559/057', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 58, 'first_name' => 'Believe', 'last_name' => 'Kanu', 'gender' => 'male', 'date_of_birth' => '2024-06-19', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 01:04:05', 'approved' => 1, 'user_id' => 60, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/058', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 59, 'first_name' => 'Amazing', 'last_name' => 'Kanu', 'gender' => 'female', 'date_of_birth' => '2024-06-19', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 01:04:58', 'approved' => 1, 'user_id' => 61, 'middle_name' => 'Amarachi', 'parent_name' => '', 'reg_no' => 'AAIS/0559/059', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 60, 'first_name' => 'Chukwuemeka', 'last_name' => 'Chibuzo', 'gender' => 'male', 'date_of_birth' => '2024-06-19', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 01:06:07', 'approved' => 1, 'user_id' => 62, 'middle_name' => 'Michael', 'parent_name' => '', 'reg_no' => 'AAIS/0559/060', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 61, 'first_name' => 'Light', 'last_name' => 'Chinyeaka', 'gender' => 'male', 'date_of_birth' => '2024-06-19', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 01:07:51', 'approved' => 1, 'user_id' => 63, 'middle_name' => 'Chizaram', 'parent_name' => '', 'reg_no' => 'AAIS/0559/061', 'profile_pic' => '/static/images/uploads/profile_pics/61_school_logo_3.jpg', 'parent_phone_number' => NULL],
                ['id' => 62, 'first_name' => 'Chisom', 'last_name' => 'Chinedu', 'gender' => 'female', 'date_of_birth' => '2024-06-19', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 01:08:45', 'approved' => 1, 'user_id' => 64, 'middle_name' => 'Christabel', 'parent_name' => '', 'reg_no' => 'AAIS/0559/062', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 63, 'first_name' => 'Esther', 'last_name' => 'Asoegwu', 'gender' => 'female', 'date_of_birth' => '2024-06-19', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 01:09:26', 'approved' => 1, 'user_id' => 65, 'middle_name' => 'Kosisochukwu', 'parent_name' => '', 'reg_no' => 'AAIS/0559/063', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 64, 'first_name' => 'Somotochukwu', 'last_name' => 'Eze', 'gender' => 'male', 'date_of_birth' => '2024-06-19', 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-19 01:10:33', 'approved' => 1, 'user_id' => 66, 'middle_name' => 'Destiny', 'parent_name' => '', 'reg_no' => 'AAIS/0559/064', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 65, 'first_name' => 'Victoria', 'last_name' => 'Uwadiegwu', 'gender' => 'Female', 'date_of_birth' => '2012-02-23', 'address' => '291 Yellow Avenue, Abayi Aba', 'parent_occupation' => 'Trader', 'state_of_origin' => 'Imo state', 'local_government_area' => 'Ahiara Ahiazu Mbaise', 'religion' => 'Christianity', 'date_registered' => '2024-06-19 11:54:23', 'approved' => 1, 'user_id' => 67, 'middle_name' => 'Chizitere', 'parent_name' => 'Uwadiegwu chinwe', 'reg_no' => 'AAIS/0559/065', 'profile_pic' => '/static/images/uploads/profile_pics/65_school_logo_3.jpg', 'parent_phone_number' => NULL],
                ['id' => 66, 'first_name' => 'Prevailer', 'last_name' => 'Ekene', 'gender' => 'female', 'date_of_birth' => '2013-05-09', 'address' => 'Alaukwu', 'parent_occupation' => 'Pharmacy', 'state_of_origin' => 'Imo state', 'local_government_area' => 'Ihioma orlu', 'religion' => 'Christianity', 'date_registered' => '2024-06-19 12:07:47', 'approved' => 1, 'user_id' => 68, 'middle_name' => 'Chimnadindu', 'parent_name' => 'Ekene eboh', 'reg_no' => 'AAIS/0559/066', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 67, 'first_name' => 'Beauty', 'last_name' => 'Ime', 'gender' => 'female', 'date_of_birth' => '2011-11-24', 'address' => '', 'parent_occupation' => 'Police Man', 'state_of_origin' => 'Akwa ibom', 'local_government_area' => '', 'religion' => 'Christianity', 'date_registered' => '2024-06-19 12:17:18', 'approved' => 1, 'user_id' => 69, 'middle_name' => 'Chidinma', 'parent_name' => 'Ime Emmanuel', 'reg_no' => 'AAIS/0559/067', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 68, 'first_name' => 'Chidiebube', 'last_name' => 'Chibuzo', 'gender' => 'male', 'date_of_birth' => '2014-02-01', 'address' => 'No 7 udezuka street', 'parent_occupation' => 'Banker', 'state_of_origin' => 'Imo state', 'local_government_area' => 'Abom mbaise', 'religion' => 'Christianity', 'date_registered' => '2024-06-19 12:42:12', 'approved' => 1, 'user_id' => 70, 'middle_name' => 'Kingsley', 'parent_name' => 'Anosike Anulika Dominica', 'reg_no' => 'AAIS/0559/068', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 70, 'first_name' => 'Oluchukwu', 'last_name' => 'Okoye', 'gender' => 'female', 'date_of_birth' => '2012-12-12', 'address' => 'No 33 Agalaba', 'parent_occupation' => 'Trade', 'state_of_origin' => 'Anambra', 'local_government_area' => 'Nneofia', 'religion' => 'Christianity', 'date_registered' => '2024-06-19 12:51:08', 'approved' => 1, 'user_id' => 72, 'middle_name' => 'Esther', 'parent_name' => 'Ndubueze', 'reg_no' => 'AAIS/0559/070', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 71, 'first_name' => 'Olivia', 'last_name' => 'Gideon', 'gender' => 'female', 'date_of_birth' => '2014-06-07', 'address' => 'No 9 Umunwankwo street', 'parent_occupation' => 'Lecturing', 'state_of_origin' => 'Abia state', 'local_government_area' => 'Isiala Ngwa', 'religion' => 'Christianity', 'date_registered' => '2024-06-19 13:06:53', 'approved' => 1, 'user_id' => 73, 'middle_name' => 'Somtochi', 'parent_name' => 'Gideon Ngozi Sunday', 'reg_no' => 'AAIS/0559/071', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 72, 'first_name' => 'Prince Charles', 'last_name' => 'Asoegwu', 'gender' => 'male', 'date_of_birth' => '2012-08-26', 'address' => 'No 271 Aba Owerri Road', 'parent_occupation' => 'Navy Man', 'state_of_origin' => 'Anambra', 'local_government_area' => 'Nnewi', 'religion' => 'Christianity', 'date_registered' => '2024-06-19 13:19:51', 'approved' => 1, 'user_id' => 74, 'middle_name' => 'Ugochukwu', 'parent_name' => 'Asoegwu Jeremiah', 'reg_no' => 'AAIS/0559/072', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 73, 'first_name' => 'Delight', 'last_name' => 'Ezereibe', 'gender' => 'female', 'date_of_birth' => '2012-08-06', 'address' => 'No 4 MCC Road', 'parent_occupation' => 'Business woman', 'state_of_origin' => 'Imo state', 'local_government_area' => 'Oru East', 'religion' => 'Christianity', 'date_registered' => '2024-06-19 13:34:09', 'approved' => 1, 'user_id' => 75, 'middle_name' => 'Ujunwa', 'parent_name' => 'Loveth Chidinma Ezeribe', 'reg_no' => 'AAIS/0559/073', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 74, 'first_name' => 'Chimaobi', 'last_name' => 'Uwadiegwu', 'gender' => 'male', 'date_of_birth' => '2011-03-27', 'address' => '291 yellow avenue', 'parent_occupation' => 'Business Man', 'state_of_origin' => 'Imo state', 'local_government_area' => 'Ahiara Ahiazu Mbaise', 'religion' => 'Christianity', 'date_registered' => '2024-06-19 13:47:12', 'approved' => 1, 'user_id' => 76, 'middle_name' => 'David', 'parent_name' => 'Uwadiegwu Chinemerem', 'reg_no' => 'AAIS/0559/074', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 76, 'first_name' => 'Ime', 'last_name' => 'Goodluck', 'gender' => 'male', 'date_of_birth' => '2008-12-03', 'address' => 'Osisioma Barack', 'parent_occupation' => 'Police woman', 'state_of_origin' => 'Akwa Ibom', 'local_government_area' => '', 'religion' => 'Christianity', 'date_registered' => '2024-06-19 14:09:27', 'approved' => 1, 'user_id' => 78, 'middle_name' => 'Chiweotito', 'parent_name' => 'Lynda ime', 'reg_no' => 'AAIS/0559/076', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 78, 'first_name' => 'Precious', 'last_name' => 'Ekene', 'gender' => 'female', 'date_of_birth' => '2011-08-01', 'address' => 'Elebele', 'parent_occupation' => 'Pharmacy', 'state_of_origin' => 'Imo state', 'local_government_area' => 'Ihioma orlu', 'religion' => 'Christianity', 'date_registered' => '2024-06-25 16:12:11', 'approved' => 1, 'user_id' => 87, 'middle_name' => 'Adaeze', 'parent_name' => 'Ekene eboh', 'reg_no' => 'AAIS/0559/078', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 81, 'first_name' => 'Destiny', 'last_name' => 'Chiemela', 'gender' => 'female', 'date_of_birth' => '2012-07-30', 'address' => 'Uratta', 'parent_occupation' => 'Painter', 'state_of_origin' => 'Abia', 'local_government_area' => 'Isiala Ngwa south', 'religion' => 'Christianity', 'date_registered' => '2024-06-27 13:58:39', 'approved' => 1, 'user_id' => 91, 'middle_name' => 'Chigozirim', 'parent_name' => 'Mr Chiemela George', 'reg_no' => 'AAIS/0559/081', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 82, 'first_name' => 'Chijindu', 'last_name' => 'Williams', 'gender' => 'male', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-06-27 14:12:02', 'approved' => 1, 'user_id' => 92, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/082', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 83, 'first_name' => 'Chimamanda', 'last_name' => 'Chibuzo', 'gender' => 'female', 'date_of_birth' => '2017-11-10', 'address' => 'No 7 udezuka street', 'parent_occupation' => 'Banker', 'state_of_origin' => 'Imo state', 'local_government_area' => 'Abom mbaise', 'religion' => 'Christianity', 'date_registered' => '2024-06-27 14:17:19', 'approved' => 1, 'user_id' => 93, 'middle_name' => 'Daniela', 'parent_name' => 'Anulika Anosike Dominica', 'reg_no' => 'AAIS/0559/083', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 84, 'first_name' => 'Glory', 'last_name' => 'Uwadiegwu', 'gender' => 'female', 'date_of_birth' => '2007-12-29', 'address' => 'Yellow avenue', 'parent_occupation' => 'Business woman', 'state_of_origin' => 'Imo state', 'local_government_area' => 'Mbaise', 'religion' => 'Christianity', 'date_registered' => '2024-07-02 12:37:01', 'approved' => 1, 'user_id' => 94, 'middle_name' => 'Ogochukwu', 'parent_name' => 'Chinwe', 'reg_no' => 'AAIS/0559/084', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 85, 'first_name' => 'Success', 'last_name' => 'Israel', 'gender' => 'male', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-07-15 12:32:12', 'approved' => 1, 'user_id' => 95, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/085', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 86, 'first_name' => 'Sochima', 'last_name' => 'Samuel', 'gender' => 'female', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-07-26 09:33:22', 'approved' => 1, 'user_id' => 96, 'middle_name' => 'Kindness', 'parent_name' => '', 'reg_no' => 'AAIS/0559/086', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 87, 'first_name' => 'Joshua', 'last_name' => 'Iheanyi', 'gender' => 'male', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-11-10 13:19:27', 'approved' => 1, 'user_id' => 98, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/087', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 88, 'first_name' => 'Stanley', 'last_name' => 'Alexander', 'gender' => 'male', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-11-10 13:22:12', 'approved' => 1, 'user_id' => 99, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/088', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 89, 'first_name' => 'Excel', 'last_name' => 'Joseph', 'gender' => 'male', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-11-12 17:42:27', 'approved' => 1, 'user_id' => 100, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/089', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 90, 'first_name' => 'Royalty', 'last_name' => 'Anosike', 'gender' => 'male', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-11-12 17:42:54', 'approved' => 1, 'user_id' => 101, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/090', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 91, 'first_name' => 'Wisdom', 'last_name' => 'Augustine', 'gender' => 'male', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-11-12 17:43:21', 'approved' => 1, 'user_id' => 102, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/091', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 92, 'first_name' => 'Miracle', 'last_name' => 'John', 'gender' => 'male', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-11-12 17:43:54', 'approved' => 1, 'user_id' => 103, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/092', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 93, 'first_name' => 'Onyinyechi', 'last_name' => 'Augustine', 'gender' => 'female', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-11-12 17:44:38', 'approved' => 1, 'user_id' => 104, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/093', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 94, 'first_name' => 'Emmanuel', 'last_name' => 'Joseph', 'gender' => 'male', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-11-12 17:45:09', 'approved' => 1, 'user_id' => 105, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/094', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 95, 'first_name' => 'Chijindu', 'last_name' => 'Sunday', 'gender' => 'female', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-11-12 17:53:10', 'approved' => 1, 'user_id' => 106, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/095', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 96, 'first_name' => 'Great', 'last_name' => 'Augustine', 'gender' => 'male', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-11-12 17:54:13', 'approved' => 1, 'user_id' => 107, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/096', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 99, 'first_name' => 'Munachimso', 'last_name' => 'David', 'gender' => 'female', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2024-11-12 17:58:40', 'approved' => 1, 'user_id' => 110, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/099', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 104, 'first_name' => 'Mkpuruoma', 'last_name' => 'Chigozie', 'gender' => 'female', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '0000-00-00 00:00:00', 'approved' => 1, 'user_id' => 115, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/104', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 107, 'first_name' => 'Joyful', 'last_name' => 'Praise', 'gender' => 'male', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '0000-00-00 00:00:00', 'approved' => 1, 'user_id' => 118, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/107', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 108, 'first_name' => 'David', 'last_name' => 'Onyenwe', 'gender' => 'male', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '0000-00-00 00:00:00', 'approved' => 1, 'user_id' => 119, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/108', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 118, 'first_name' => 'Wealth', 'last_name' => 'Christopher', 'gender' => 'male', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2025-03-03 14:47:09', 'approved' => 1, 'user_id' => 139, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/118', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 119, 'first_name' => 'Covenant', 'last_name' => 'Izuchukwu', 'gender' => 'male', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2025-03-03 14:47:46', 'approved' => 1, 'user_id' => 140, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/119', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 120, 'first_name' => 'Miracle', 'last_name' => 'Emmanuel', 'gender' => 'female', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2025-03-03 14:48:44', 'approved' => 1, 'user_id' => 141, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/120', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 121, 'first_name' => 'David', 'last_name' => 'Udo', 'gender' => 'male', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2025-03-03 14:49:21', 'approved' => 1, 'user_id' => 142, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/121', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 122, 'first_name' => 'Christable', 'last_name' => 'Nwokeocha', 'gender' => 'female', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2025-03-03 14:52:27', 'approved' => 1, 'user_id' => 143, 'middle_name' => 'Zimchikachukwu', 'parent_name' => '', 'reg_no' => 'AAIS/0559/122', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 123, 'first_name' => 'Wisdom', 'last_name' => 'Christopher', 'gender' => 'male', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2025-03-03 14:52:58', 'approved' => 1, 'user_id' => 144, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/123', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 124, 'first_name' => 'Miracle', 'last_name' => 'Udo', 'gender' => 'female', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => '', 'state_of_origin' => '', 'local_government_area' => '', 'religion' => '', 'date_registered' => '2025-03-03 14:54:25', 'approved' => 1, 'user_id' => 145, 'middle_name' => '', 'parent_name' => '', 'reg_no' => 'AAIS/0559/124', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 126, 'first_name' => 'Samuel', 'last_name' => 'Udo', 'gender' => 'male', 'date_of_birth' => NULL, 'address' => '', 'parent_occupation' => NULL, 'state_of_origin' => '', 'local_government_area' => '', 'religion' => NULL, 'date_registered' => '2025-03-25 07:26:03', 'approved' => 0, 'user_id' => 155, 'middle_name' => '', 'parent_name' => NULL, 'reg_no' => 'AAIS/0559/126', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 127, 'first_name' => 'Goodnews', 'last_name' => 'Ukam', 'gender' => 'female', 'date_of_birth' => '2011-03-03', 'address' => '', 'parent_occupation' => NULL, 'state_of_origin' => 'Cross Rivers', 'local_government_area' => '', 'religion' => NULL, 'date_registered' => '2025-03-26 16:25:01', 'approved' => 0, 'user_id' => 156, 'middle_name' => 'Owai', 'parent_name' => NULL, 'reg_no' => 'AAIS/0559/127', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
                ['id' => 128, 'first_name' => 'Awesome', 'last_name' => 'Chigbu', 'gender' => 'male', 'date_of_birth' => '2013-04-03', 'address' => '', 'parent_occupation' => NULL, 'state_of_origin' => 'Abia', 'local_government_area' => 'Osisioma', 'religion' => NULL, 'date_registered' => '2025-03-26 16:37:06', 'approved' => 0, 'user_id' => 157, 'middle_name' => 'Chinaza', 'parent_name' => NULL, 'reg_no' => 'AAIS/0559/128', 'profile_pic' => NULL, 'parent_phone_number' => NULL],
            ];

            $now = now()->toDateTimeString();

            // Disable auto-increment temporarily to preserve IDs
            DB::statement('ALTER TABLE students AUTO_INCREMENT = 7');

            // Insert students
            foreach ($students as $student) {
                DB::table('students')->insert([
                    'id' => $student['id'],
                    'first_name' => $student['first_name'],
                    'last_name' => $student['last_name'],
                    'gender' => $student['gender'],
                    'date_of_birth' => $student['date_of_birth'],
                    'address' => $student['address'],
                    'parent_occupation' => $student['parent_occupation'],
                    'state_of_origin' => $student['state_of_origin'],
                    'local_government_area' => $student['local_government_area'],
                    'religion' => $student['religion'],
                    'date_registered' => $student['date_registered'] === '0000-00-00 00:00:00' ? $now : $student['date_registered'],
                    'approved' => $student['approved'],
                    'user_id' => $student['user_id'],
                    'middle_name' => $student['middle_name'],
                    'parent_name' => $student['parent_name'],
                    'reg_no' => $student['reg_no'],
                    'profile_pic' => $student['profile_pic'],
                    'parent_phone_number' => $student['parent_phone_number'],
                ]);
                $this->info("Imported student: {$student['first_name']} {$student['last_name']} (ID: {$student['id']})");
                Log::info("Imported student: {$student['first_name']} {$student['last_name']} (ID: {$student['id']})");
            }

            // Set auto-increment to max ID + 1
            $maxId = max(array_column($students, 'id'));
            DB::statement("ALTER TABLE students AUTO_INCREMENT = " . ($maxId + 1));

            $this->info("Students imported successfully. Auto-increment set to " . ($maxId + 1));
        } catch (\Exception $e) {
            Log::error("Error importing students: {$e->getMessage()}");
            $this->error("Error: {$e->getMessage()}");
            return 1;
        }

        return 0;
    }
}
