<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class ImportClassSubjects extends Command
{
    protected $signature = 'import:class-subjects';
    protected $description = 'Import class subjects from Flask database';

    public function handle()
    {
        try {
            // Truncate the class_subject table to avoid conflicts
            DB::statement('SET FOREIGN_KEY_CHECKS=0;');
            DB::table('class_subject')->truncate();
            DB::statement('SET FOREIGN_KEY_CHECKS=1;');
            $this->info('Truncated class_subject table');
            Log::info('Truncated class_subject table');

            // Class subject data
            $classSubjects = [
                ['class_id' => 1, 'subject_id' => 41],
                ['class_id' => 2, 'subject_id' => 41],
                ['class_id' => 3, 'subject_id' => 41],
                ['class_id' => 4, 'subject_id' => 41],
                ['class_id' => 6, 'subject_id' => 41],
                ['class_id' => 1, 'subject_id' => 44],
                ['class_id' => 2, 'subject_id' => 44],
                ['class_id' => 3, 'subject_id' => 44],
                ['class_id' => 4, 'subject_id' => 44],
                ['class_id' => 6, 'subject_id' => 44],
                ['class_id' => 5, 'subject_id' => 49],
                ['class_id' => 10, 'subject_id' => 49],
                ['class_id' => 12, 'subject_id' => 49],
                ['class_id' => 2, 'subject_id' => 59],
                ['class_id' => 1, 'subject_id' => 72],
                ['class_id' => 2, 'subject_id' => 72],
                ['class_id' => 3, 'subject_id' => 72],
                ['class_id' => 4, 'subject_id' => 72],
                ['class_id' => 6, 'subject_id' => 72],
                ['class_id' => 1, 'subject_id' => 117],
                ['class_id' => 2, 'subject_id' => 117],
                ['class_id' => 3, 'subject_id' => 117],
                ['class_id' => 4, 'subject_id' => 117],
                ['class_id' => 6, 'subject_id' => 117],
                ['class_id' => 1, 'subject_id' => 118],
                ['class_id' => 2, 'subject_id' => 118],
                ['class_id' => 3, 'subject_id' => 118],
                ['class_id' => 4, 'subject_id' => 118],
                ['class_id' => 6, 'subject_id' => 118],
                ['class_id' => 2, 'subject_id' => 120],
                ['class_id' => 14, 'subject_id' => 127],
                ['class_id' => 14, 'subject_id' => 128],
                ['class_id' => 14, 'subject_id' => 130],
                ['class_id' => 14, 'subject_id' => 132],
                ['class_id' => 5, 'subject_id' => 200],
                ['class_id' => 7, 'subject_id' => 200],
                ['class_id' => 8, 'subject_id' => 200],
                ['class_id' => 9, 'subject_id' => 200],
                ['class_id' => 10, 'subject_id' => 200],
                ['class_id' => 11, 'subject_id' => 200],
                ['class_id' => 12, 'subject_id' => 200],
                ['class_id' => 13, 'subject_id' => 200],
                ['class_id' => 14, 'subject_id' => 200],
                ['class_id' => 5, 'subject_id' => 201],
                ['class_id' => 7, 'subject_id' => 201],
                ['class_id' => 8, 'subject_id' => 201],
                ['class_id' => 9, 'subject_id' => 201],
                ['class_id' => 10, 'subject_id' => 201],
                ['class_id' => 11, 'subject_id' => 201],
                ['class_id' => 12, 'subject_id' => 201],
                ['class_id' => 13, 'subject_id' => 201],
                ['class_id' => 14, 'subject_id' => 201],
                ['class_id' => 1, 'subject_id' => 202],
                ['class_id' => 2, 'subject_id' => 202],
                ['class_id' => 3, 'subject_id' => 202],
                ['class_id' => 4, 'subject_id' => 202],
                ['class_id' => 5, 'subject_id' => 202],
                ['class_id' => 6, 'subject_id' => 202],
                ['class_id' => 7, 'subject_id' => 202],
                ['class_id' => 8, 'subject_id' => 202],
                ['class_id' => 9, 'subject_id' => 202],
                ['class_id' => 10, 'subject_id' => 202],
                ['class_id' => 11, 'subject_id' => 202],
                ['class_id' => 12, 'subject_id' => 202],
                ['class_id' => 13, 'subject_id' => 202],
                ['class_id' => 1, 'subject_id' => 203],
                ['class_id' => 2, 'subject_id' => 203],
                ['class_id' => 3, 'subject_id' => 203],
                ['class_id' => 4, 'subject_id' => 203],
                ['class_id' => 5, 'subject_id' => 203],
                ['class_id' => 6, 'subject_id' => 203],
                ['class_id' => 7, 'subject_id' => 203],
                ['class_id' => 8, 'subject_id' => 203],
                ['class_id' => 9, 'subject_id' => 203],
                ['class_id' => 10, 'subject_id' => 203],
                ['class_id' => 11, 'subject_id' => 203],
                ['class_id' => 12, 'subject_id' => 203],
                ['class_id' => 13, 'subject_id' => 203],
                ['class_id' => 14, 'subject_id' => 203],
                ['class_id' => 1, 'subject_id' => 204],
                ['class_id' => 2, 'subject_id' => 204],
                ['class_id' => 3, 'subject_id' => 204],
                ['class_id' => 4, 'subject_id' => 204],
                ['class_id' => 5, 'subject_id' => 204],
                ['class_id' => 6, 'subject_id' => 204],
                ['class_id' => 7, 'subject_id' => 204],
                ['class_id' => 8, 'subject_id' => 204],
                ['class_id' => 9, 'subject_id' => 204],
                ['class_id' => 10, 'subject_id' => 204],
                ['class_id' => 11, 'subject_id' => 204],
                ['class_id' => 12, 'subject_id' => 204],
                ['class_id' => 13, 'subject_id' => 204],
                ['class_id' => 14, 'subject_id' => 204],
                ['class_id' => 1, 'subject_id' => 205],
                ['class_id' => 2, 'subject_id' => 205],
                ['class_id' => 3, 'subject_id' => 205],
                ['class_id' => 4, 'subject_id' => 205],
                ['class_id' => 5, 'subject_id' => 205],
                ['class_id' => 6, 'subject_id' => 205],
                ['class_id' => 7, 'subject_id' => 205],
                ['class_id' => 8, 'subject_id' => 205],
                ['class_id' => 9, 'subject_id' => 205],
                ['class_id' => 10, 'subject_id' => 205],
                ['class_id' => 11, 'subject_id' => 205],
                ['class_id' => 12, 'subject_id' => 205],
                ['class_id' => 13, 'subject_id' => 205],
                ['class_id' => 1, 'subject_id' => 206],
                ['class_id' => 2, 'subject_id' => 206],
                ['class_id' => 3, 'subject_id' => 206],
                ['class_id' => 4, 'subject_id' => 206],
                ['class_id' => 5, 'subject_id' => 206],
                ['class_id' => 6, 'subject_id' => 206],
                ['class_id' => 7, 'subject_id' => 206],
                ['class_id' => 8, 'subject_id' => 206],
                ['class_id' => 9, 'subject_id' => 206],
                ['class_id' => 10, 'subject_id' => 206],
                ['class_id' => 11, 'subject_id' => 206],
                ['class_id' => 12, 'subject_id' => 206],
                ['class_id' => 13, 'subject_id' => 206],
                ['class_id' => 14, 'subject_id' => 206],
                ['class_id' => 1, 'subject_id' => 207],
                ['class_id' => 2, 'subject_id' => 207],
                ['class_id' => 3, 'subject_id' => 207],
                ['class_id' => 4, 'subject_id' => 207],
                ['class_id' => 5, 'subject_id' => 207],
                ['class_id' => 6, 'subject_id' => 207],
                ['class_id' => 7, 'subject_id' => 207],
                ['class_id' => 8, 'subject_id' => 207],
                ['class_id' => 9, 'subject_id' => 207],
                ['class_id' => 10, 'subject_id' => 207],
                ['class_id' => 11, 'subject_id' => 207],
                ['class_id' => 12, 'subject_id' => 207],
                ['class_id' => 13, 'subject_id' => 207],
                ['class_id' => 1, 'subject_id' => 208],
                ['class_id' => 2, 'subject_id' => 208],
                ['class_id' => 3, 'subject_id' => 208],
                ['class_id' => 4, 'subject_id' => 208],
                ['class_id' => 5, 'subject_id' => 208],
                ['class_id' => 6, 'subject_id' => 208],
                ['class_id' => 7, 'subject_id' => 208],
                ['class_id' => 8, 'subject_id' => 208],
                ['class_id' => 9, 'subject_id' => 208],
                ['class_id' => 10, 'subject_id' => 208],
                ['class_id' => 11, 'subject_id' => 208],
                ['class_id' => 12, 'subject_id' => 208],
                ['class_id' => 13, 'subject_id' => 208],
                ['class_id' => 1, 'subject_id' => 210],
                ['class_id' => 2, 'subject_id' => 210],
                ['class_id' => 3, 'subject_id' => 210],
                ['class_id' => 4, 'subject_id' => 210],
                ['class_id' => 5, 'subject_id' => 210],
                ['class_id' => 6, 'subject_id' => 210],
                ['class_id' => 7, 'subject_id' => 210],
                ['class_id' => 8, 'subject_id' => 210],
                ['class_id' => 9, 'subject_id' => 210],
                ['class_id' => 10, 'subject_id' => 210],
                ['class_id' => 11, 'subject_id' => 210],
                ['class_id' => 12, 'subject_id' => 210],
                ['class_id' => 13, 'subject_id' => 210],
                ['class_id' => 5, 'subject_id' => 211],
                ['class_id' => 7, 'subject_id' => 211],
                ['class_id' => 8, 'subject_id' => 211],
                ['class_id' => 9, 'subject_id' => 211],
                ['class_id' => 10, 'subject_id' => 211],
                ['class_id' => 11, 'subject_id' => 211],
                ['class_id' => 12, 'subject_id' => 211],
                ['class_id' => 13, 'subject_id' => 211],
                ['class_id' => 5, 'subject_id' => 212],
                ['class_id' => 7, 'subject_id' => 212],
                ['class_id' => 8, 'subject_id' => 212],
                ['class_id' => 9, 'subject_id' => 212],
                ['class_id' => 10, 'subject_id' => 212],
                ['class_id' => 11, 'subject_id' => 212],
                ['class_id' => 12, 'subject_id' => 212],
                ['class_id' => 13, 'subject_id' => 212],
                ['class_id' => 1, 'subject_id' => 213],
                ['class_id' => 2, 'subject_id' => 213],
                ['class_id' => 3, 'subject_id' => 213],
                ['class_id' => 4, 'subject_id' => 213],
                ['class_id' => 6, 'subject_id' => 213],
                ['class_id' => 7, 'subject_id' => 213],
                ['class_id' => 8, 'subject_id' => 213],
                ['class_id' => 9, 'subject_id' => 213],
                ['class_id' => 10, 'subject_id' => 213],
                ['class_id' => 11, 'subject_id' => 213],
                ['class_id' => 13, 'subject_id' => 213],
                ['class_id' => 5, 'subject_id' => 214],
                ['class_id' => 7, 'subject_id' => 214],
                ['class_id' => 8, 'subject_id' => 214],
                ['class_id' => 9, 'subject_id' => 214],
                ['class_id' => 10, 'subject_id' => 214],
                ['class_id' => 11, 'subject_id' => 214],
                ['class_id' => 12, 'subject_id' => 214],
                ['class_id' => 13, 'subject_id' => 214],
                ['class_id' => 1, 'subject_id' => 216],
                ['class_id' => 2, 'subject_id' => 216],
                ['class_id' => 4, 'subject_id' => 216],
                ['class_id' => 2, 'subject_id' => 217],
                ['class_id' => 7, 'subject_id' => 217],
                ['class_id' => 8, 'subject_id' => 217],
                ['class_id' => 9, 'subject_id' => 217],
                ['class_id' => 11, 'subject_id' => 217],
                ['class_id' => 13, 'subject_id' => 217],
                ['class_id' => 2, 'subject_id' => 218],
                ['class_id' => 7, 'subject_id' => 218],
                ['class_id' => 8, 'subject_id' => 218],
                ['class_id' => 9, 'subject_id' => 218],
                ['class_id' => 11, 'subject_id' => 218],
                ['class_id' => 13, 'subject_id' => 218],
                ['class_id' => 2, 'subject_id' => 219],
                ['class_id' => 5, 'subject_id' => 220],
                ['class_id' => 7, 'subject_id' => 220],
                ['class_id' => 8, 'subject_id' => 220],
                ['class_id' => 9, 'subject_id' => 220],
                ['class_id' => 10, 'subject_id' => 220],
                ['class_id' => 11, 'subject_id' => 220],
                ['class_id' => 12, 'subject_id' => 220],
                ['class_id' => 13, 'subject_id' => 220],
                ['class_id' => 1, 'subject_id' => 221],
                ['class_id' => 2, 'subject_id' => 221],
                ['class_id' => 3, 'subject_id' => 221],
                ['class_id' => 4, 'subject_id' => 221],
                ['class_id' => 6, 'subject_id' => 221],
                ['class_id' => 7, 'subject_id' => 221],
                ['class_id' => 8, 'subject_id' => 221],
                ['class_id' => 9, 'subject_id' => 221],
                ['class_id' => 11, 'subject_id' => 221],
                ['class_id' => 13, 'subject_id' => 221],
            ];

            $now = now()->toDateTimeString();

            // Insert class subjects
            foreach ($classSubjects as $classSubject) {
                DB::table('class_subject')->insert([
                    'class_id' => $classSubject['class_id'],
                    'subject_id' => $classSubject['subject_id'],
                    'created_at' => $now,
                    'updated_at' => $now
                ]);
                $this->info("Imported class subject: class_id {$classSubject['class_id']}, subject_id {$classSubject['subject_id']}");
                Log::info("Imported class subject: class_id {$classSubject['class_id']}, subject_id {$classSubject['subject_id']}");
            }

            $this->info("Class subjects imported successfully.");
        } catch (\Exception $e) {
            Log::error("Error importing class subjects: {$e->getMessage()}");
            $this->error("Error: {$e->getMessage()}");
            return 1;
        }

        return 0;
    }
}
