<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class ImportFeePayment extends Command
{
    protected $signature = 'import:fee-payment';
    protected $description = 'Import fee payment data from Flask database';

    public function handle()
    {
        try {
            // Truncate the fee_payment table to avoid conflicts
            DB::statement('SET FOREIGN_KEY_CHECKS=0;');
            DB::table('fee_payments')->truncate();
            DB::statement('SET FOREIGN_KEY_CHECKS=1;');
            $this->info('Truncated fee_payments table');
            Log::info('Truncated fee_payments table');

            // Fee payment data
            $feePayments = [
                ['id' => 1, 'student_id' => 7, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 2, 'student_id' => 9, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 3, 'student_id' => 11, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 4, 'student_id' => 12, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 5, 'student_id' => 15, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 6, 'student_id' => 16, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 7, 'student_id' => 21, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 8, 'student_id' => 22, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 9, 'student_id' => 23, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 10, 'student_id' => 24, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 11, 'student_id' => 25, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 12, 'student_id' => 26, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 13, 'student_id' => 27, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 14, 'student_id' => 29, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 15, 'student_id' => 30, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 16, 'student_id' => 32, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 17, 'student_id' => 36, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 18, 'student_id' => 39, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 19, 'student_id' => 40, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 20, 'student_id' => 42, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 21, 'student_id' => 43, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 22, 'student_id' => 44, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 23, 'student_id' => 46, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 25, 'student_id' => 49, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 26, 'student_id' => 51, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 27, 'student_id' => 55, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 28, 'student_id' => 56, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 29, 'student_id' => 57, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 30, 'student_id' => 58, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 31, 'student_id' => 59, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 32, 'student_id' => 63, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 33, 'student_id' => 64, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 34, 'student_id' => 65, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 35, 'student_id' => 72, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 36, 'student_id' => 73, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 37, 'student_id' => 74, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 38, 'student_id' => 84, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 39, 'student_id' => 87, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 40, 'student_id' => 88, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 41, 'student_id' => 89, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 42, 'student_id' => 90, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 43, 'student_id' => 94, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 44, 'student_id' => 95, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 45, 'student_id' => 99, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 47, 'student_id' => 92, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 48, 'student_id' => 17, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 49, 'student_id' => 38, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 50, 'student_id' => 53, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 51, 'student_id' => 54, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 52, 'student_id' => 19, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 53, 'student_id' => 35, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 54, 'student_id' => 61, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 55, 'student_id' => 31, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 56, 'student_id' => 33, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 57, 'student_id' => 104, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 58, 'student_id' => 107, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 0],
                ['id' => 59, 'student_id' => 48, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 60, 'student_id' => 71, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 61, 'student_id' => 119, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 62, 'student_id' => 108, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 63, 'student_id' => 107, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 64, 'student_id' => 104, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 65, 'student_id' => 118, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 66, 'student_id' => 95, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 67, 'student_id' => 96, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 68, 'student_id' => 120, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 69, 'student_id' => 99, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 70, 'student_id' => 7, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 71, 'student_id' => 15, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 72, 'student_id' => 122, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 73, 'student_id' => 11, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 74, 'student_id' => 12, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 75, 'student_id' => 90, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 76, 'student_id' => 9, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 77, 'student_id' => 123, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 78, 'student_id' => 23, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 79, 'student_id' => 22, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 80, 'student_id' => 25, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 81, 'student_id' => 21, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 82, 'student_id' => 24, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 83, 'student_id' => 19, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 84, 'student_id' => 29, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 85, 'student_id' => 36, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 86, 'student_id' => 40, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 87, 'student_id' => 35, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 88, 'student_id' => 39, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 89, 'student_id' => 42, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 90, 'student_id' => 87, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 91, 'student_id' => 46, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 92, 'student_id' => 49, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 93, 'student_id' => 54, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 94, 'student_id' => 48, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 95, 'student_id' => 51, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 96, 'student_id' => 59, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 97, 'student_id' => 57, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 98, 'student_id' => 58, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 99, 'student_id' => 55, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 100, 'student_id' => 64, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 101, 'student_id' => 61, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 102, 'student_id' => 73, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 103, 'student_id' => 74, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 104, 'student_id' => 65, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 105, 'student_id' => 84, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 106, 'student_id' => 108, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 107, 'student_id' => 96, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 108, 'student_id' => 93, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 109, 'student_id' => 91, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 110, 'student_id' => 28, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 111, 'student_id' => 83, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 112, 'student_id' => 85, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 113, 'student_id' => 60, 'session_id' => 2, 'term' => 'First', 'has_paid_fee' => 1],
                ['id' => 114, 'student_id' => 8, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 115, 'student_id' => 13, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 116, 'student_id' => 7, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 117, 'student_id' => 15, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 118, 'student_id' => 95, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 119, 'student_id' => 16, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 120, 'student_id' => 11, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 121, 'student_id' => 12, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 122, 'student_id' => 86, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 123, 'student_id' => 9, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 124, 'student_id' => 10, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 125, 'student_id' => 27, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 126, 'student_id' => 19, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 127, 'student_id' => 24, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 128, 'student_id' => 20, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 129, 'student_id' => 18, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 130, 'student_id' => 21, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 131, 'student_id' => 22, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 132, 'student_id' => 25, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 133, 'student_id' => 26, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 134, 'student_id' => 89, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 135, 'student_id' => 17, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 136, 'student_id' => 30, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 137, 'student_id' => 34, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 138, 'student_id' => 31, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 139, 'student_id' => 32, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 140, 'student_id' => 29, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 141, 'student_id' => 28, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 142, 'student_id' => 23, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 143, 'student_id' => 94, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 144, 'student_id' => 39, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 145, 'student_id' => 38, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 146, 'student_id' => 14, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 147, 'student_id' => 35, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 148, 'student_id' => 33, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 149, 'student_id' => 36, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 150, 'student_id' => 37, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 151, 'student_id' => 41, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 152, 'student_id' => 51, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 153, 'student_id' => 88, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 154, 'student_id' => 46, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 155, 'student_id' => 42, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 156, 'student_id' => 44, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 157, 'student_id' => 40, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 158, 'student_id' => 82, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 159, 'student_id' => 83, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 160, 'student_id' => 43, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 161, 'student_id' => 47, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 162, 'student_id' => 49, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 163, 'student_id' => 54, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 164, 'student_id' => 53, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 165, 'student_id' => 52, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 166, 'student_id' => 50, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 167, 'student_id' => 85, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 168, 'student_id' => 56, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 169, 'student_id' => 48, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 170, 'student_id' => 59, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 171, 'student_id' => 58, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 172, 'student_id' => 55, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 173, 'student_id' => 60, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 174, 'student_id' => 57, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 175, 'student_id' => 62, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 176, 'student_id' => 63, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 177, 'student_id' => 61, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 178, 'student_id' => 64, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 179, 'student_id' => 68, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 180, 'student_id' => 73, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 181, 'student_id' => 70, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 182, 'student_id' => 72, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 183, 'student_id' => 67, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 184, 'student_id' => 74, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 185, 'student_id' => 81, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 186, 'student_id' => 66, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 187, 'student_id' => 65, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 188, 'student_id' => 84, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 189, 'student_id' => 76, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 190, 'student_id' => 78, 'session_id' => 1, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 191, 'student_id' => 16, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 192, 'student_id' => 83, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 193, 'student_id' => 60, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 194, 'student_id' => 68, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 195, 'student_id' => 31, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 196, 'student_id' => 92, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 197, 'student_id' => 91, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 198, 'student_id' => 93, 'session_id' => 2, 'term' => 'Second', 'has_paid_fee' => 1],
                ['id' => 199, 'student_id' => 48, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 200, 'student_id' => 120, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 201, 'student_id' => 119, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 0],
                ['id' => 202, 'student_id' => 21, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 203, 'student_id' => 42, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 204, 'student_id' => 90, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 205, 'student_id' => 19, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 206, 'student_id' => 35, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 207, 'student_id' => 61, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 208, 'student_id' => 118, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 209, 'student_id' => 123, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 210, 'student_id' => 99, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 211, 'student_id' => 59, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 212, 'student_id' => 58, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 213, 'student_id' => 7, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 214, 'student_id' => 122, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 215, 'student_id' => 15, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 216, 'student_id' => 107, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 217, 'student_id' => 55, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 218, 'student_id' => 64, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 219, 'student_id' => 104, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 220, 'student_id' => 24, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 221, 'student_id' => 39, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 222, 'student_id' => 51, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 223, 'student_id' => 57, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 224, 'student_id' => 16, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 225, 'student_id' => 11, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 226, 'student_id' => 12, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 227, 'student_id' => 92, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 228, 'student_id' => 9, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 229, 'student_id' => 23, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 230, 'student_id' => 22, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 231, 'student_id' => 25, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 232, 'student_id' => 29, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 233, 'student_id' => 31, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 234, 'student_id' => 36, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 235, 'student_id' => 40, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 236, 'student_id' => 87, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 237, 'student_id' => 46, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 238, 'student_id' => 49, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 239, 'student_id' => 73, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 240, 'student_id' => 127, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 241, 'student_id' => 95, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 242, 'student_id' => 65, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 243, 'student_id' => 84, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 244, 'student_id' => 83, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 245, 'student_id' => 60, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1],
                ['id' => 246, 'student_id' => 68, 'session_id' => 2, 'term' => 'Third', 'has_paid_fee' => 1]
            ];

            // Set auto-increment starting value
            DB::statement('ALTER TABLE fee_payments AUTO_INCREMENT = 1');

            // Insert data
            foreach ($feePayments as $record) {
                DB::table('fee_payments')->insert([
                    'id' => $record['id'],
                    'student_id' => $record['student_id'],
                    'session_id' => $record['session_id'],
                    'term' => $record['term'],
                    'has_paid_fee' => $record['has_paid_fee'],
                    'created_at' => now(),
                    'updated_at' => now()
                ]);
                $this->info("Imported fee_payment: ID {$record['id']} for student_id {$record['student_id']}");
                Log::info("Imported fee_payment: ID {$record['id']} for student_id {$record['student_id']}");
            }

            // Set auto-increment to max ID + 1
            $maxId = max(array_column($feePayments, 'id'));
            DB::statement("ALTER TABLE fee_payments AUTO_INCREMENT = " . ($maxId + 1));

            $this->info("Fee payment data imported successfully. Auto-increment set to " . ($maxId + 1));
        } catch (\Exception $e) {
            Log::error("Error importing fee payment: {$e->getMessage()}");
            $this->error("Error: {$e->getMessage()}");
            return 1;
        }

        return 0;
    }
}
