-- Table structure for `student`
CREATE TABLE `student` (
  `id` int NOT NULL AUTO_INCREMENT,
  `first_name` varchar(50) NOT NULL,
  `last_name` varchar(50) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(200) NOT NULL,
  `gender` varchar(10) NOT NULL,
  `date_of_birth` date DEFAULT NULL,
  `parent_phone_number` varchar(11) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `parent_occupation` varchar(100) DEFAULT NULL,
  `previous_class` varchar(50) DEFAULT NULL,
  `state_of_origin` varchar(50) DEFAULT NULL,
  `local_government_area` varchar(50) DEFAULT NULL,
  `religion` varchar(50) DEFAULT NULL,
  `date_registered` datetime DEFAULT CURRENT_TIMESTAMP,
  `approved` tinyint(1) DEFAULT NULL,
  `user_id` int DEFAULT NULL,
  `middle_name` varchar(50) DEFAULT NULL,
  `parent_name` varchar(70) DEFAULT NULL,
  `has_paid_fee` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `student_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8mb3;

-- Data for `student`
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (5, 'Helen', 'Charles ', 'helen.charles', 'mCCVEXV9', 'female', '2024-06-18', '', '', '', 'Creche', '', '', '', '2024-06-18 18:24:38', 0, 7, 'Mkpuruoma ', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (6, 'Chinenye', 'Victory', 'chinenye.victory', 'NDNN6Qfv', 'female', '2024-06-18', '', '', '', 'Creche', '', '', '', '2024-06-18 18:26:46', 0, 8, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (7, 'Ogochukwu', 'Okoye', 'ogochukwu.okoye', 'xpnxtn6J', 'female', '2024-06-18', '', '', '', 'Creche', '', '', '', '2024-06-18 18:27:38', 0, 9, 'Obioma', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (8, 'David', 'Ndubueze', 'david.ndubueze', '2gNRYTeV', 'male', '2024-06-18', '', '', '', 'Creche', '', '', '', '2024-06-18 18:28:13', 0, 10, 'Chidiebube ', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (9, 'Taylor', 'Imeole', 'taylor.imeole', 'mPzgOCqN', 'male', '2024-06-18', '', '', '', 'Creche', '', '', '', '2024-06-18 18:29:14', 1, 11, 'Ayor', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (10, 'Temple', 'Williams', 'temple.williams', 'GoAK3cbm', 'male', '2024-06-18', '', '', '', 'Creche', '', '', '', '2024-06-18 18:30:56', 1, 12, 'Akachukwu', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (11, 'Jadon', 'Nwoji', 'jadon.nwoji', 'LBMwAX41', 'male', '2024-06-18', '', '', '', 'Creche', '', '', '', '2024-06-18 18:32:07', 1, 13, 'Chukwudi', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (12, 'Joshua ', 'Nwoji', 'joshua.nwoji', 'MQ15gqSw', 'male', '2024-06-18', '', '', '', 'Creche', '', '', '', '2024-06-18 18:32:59', 1, 14, 'Chimeremeze', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (13, 'Ezinne', 'Chinenye ', 'ezinne.chinenye', 'gNEwSKBq', 'female', '2024-06-18', '', '', '', 'Creche', '', '', '', '2024-06-18 18:33:45', 1, 15, 'Esther', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (14, 'John', 'Miracle ', 'john.miracle', 'aQY1dkjv', 'male', '2024-06-18', '', '', '', 'Creche', '', '', '', '2024-06-18 18:34:16', 1, 16, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (15, 'Adaeze ', 'Okechukwu', 'adaeze.okechukwu', 'jRsa0ffv', 'female', '2024-06-18', '', '', '', 'Creche', '', '', '', '2024-06-18 18:35:04', 1, 17, 'Nnennaya', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (16, 'Ikechukwu', 'Chukwubuikem', 'ikechukwu.chukwubuikem', 'HrewNB4h', 'male', '2024-06-18', '', '', '', 'Creche', '', '', '', '2024-06-18 18:35:56', 1, 18, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (17, 'Goodluck', 'Nwankpa', 'goodluck.nwankpa', 'hdX60ogx', 'male', '2024-06-18', '', '', '', 'Pre-Nursery', '', '', '', '2024-06-18 18:50:18', 1, 19, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (18, 'Wisdom', 'Ndubueze ', 'wisdom.ndubueze', 'RKtUtizz', 'male', '2024-06-18', '', '', '', 'Pre-Nursery', '', '', '', '2024-06-18 18:51:00', 1, 20, 'Chijindu', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (19, 'Wisdom ', 'Chinyeaka', 'wisdom.chinyeaka', 'kftmiW9w', 'male', '2024-06-18', '', '', '', 'Pre-Nursery', '', '', '', '2024-06-18 18:51:43', 1, 21, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (20, 'Oluchukwu', 'Chinedu', 'oluchukwu.chinedu', 'cS2gWINc', 'female', '2024-06-18', '', '', '', 'Pre-Nursery', '', '', '', '2024-06-18 18:52:53', 1, 22, 'Jessica', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (21, 'Miracle ', 'Ezeribe', 'miracle.ezeribe', 'WFu5ByOR', 'female', '2024-06-18', '', '', '', 'Pre-Nursery', '', '', '', '2024-06-18 18:54:43', 1, 23, 'Ifunaya', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (22, 'Ifunanya', 'Charles', 'ifunanya.charles', 'wqVxvtEF', 'female', '2024-06-18', '', '', '', 'Pre-Nursery', '', '', '', '2024-06-18 18:56:02', 1, 24, 'Exceedinggrace', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (23, 'Elder ', 'udochukwu', 'elder.udochukwu', 'seL9qo8v', 'male', '2024-06-18', '', '', '', 'Pre-Nursery', '', '', '', '2024-06-18 18:56:41', 1, 25, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (24, 'Special ', 'Chidi', 'special.chidi', 'mktDPBiM', 'male', '2024-06-18', '', '', '', 'Pre-Nursery', '', '', '', '2024-06-18 18:57:09', 1, 26, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (25, 'Ijeoma', 'Moses', 'ijeoma.moses', '4oi0AVxX', 'female', '2024-06-18', '', '', '', 'Pre-Nursery', '', '', '', '2024-06-18 18:57:48', 1, 27, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (26, 'Genevieve ', 'Joseph ', 'genevieve.joseph', 'PLZb3IuI', 'female', '2024-06-18', '', '', '', 'Pre-Nursery', '', '', '', '2024-06-18 18:58:15', 1, 28, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (27, 'David ', 'Asoegwu', 'david.asoegwu', 'nCg4tmIg', 'male', '2024-06-18', '', '', '', 'Pre-Nursery', '', '', '', '2024-06-18 18:58:42', 1, 29, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (28, 'DivineFavour', 'Israel ', 'divinefavour.israel', '4RYQpoea', 'female', '2024-06-18', '', '', '', 'Nursery 1', '', '', '', '2024-06-18 19:01:52', 1, 30, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (29, 'Emmanuel ', 'Divine', 'emmanuel.divine', 'E4flNR4W', 'female', '2024-06-18', '', '', '', 'Nursery 1', '', '', '', '2024-06-18 19:02:41', 1, 31, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (30, 'MaryJane', 'Joseph ', 'maryjane.joseph', 'pHukyH9M', 'female', '2024-06-18', '', '', '', 'Nursery 1', '', '', '', '2024-06-18 19:04:21', 1, 32, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (31, 'Gift', 'John', 'gift.john', 'QSydm9V5', 'female', '2024-06-18', '', '', '', 'Nursery 1', '', '', '', '2024-06-18 19:04:55', 1, 33, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (32, 'Excel', 'Maduabuchi', 'excel.maduabuchi', 'EQzAl2vJ', 'male', '2024-06-18', '', '', '', 'Nursery 1', '', '', '', '2024-06-18 19:12:13', 1, 34, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (33, 'Prince', 'Tochukwu', 'prince.tochukwu', 'utvRurBI', 'male', '2024-06-18', '', '', '', 'Nursery 1', '', '', '', '2024-06-18 19:13:18', 1, 35, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (34, 'Mary', 'John', 'mary.john', 'iQezoRvx', 'female', '2024-06-18', '', '', '', 'Nursery 1', '', '', '', '2024-06-18 19:14:13', 1, 36, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (35, 'Great', 'Chinyeaka', 'great.chinyeaka', 'jyI4gmT1', 'male', '2024-06-18', '', '', '', 'Nursery 2', '', '', '', '2024-06-18 19:16:23', 1, 37, 'Chibuikem', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (36, 'Adaeze ', 'Moses', 'adaeze.moses', 'Tg6sPrTO', 'female', '2024-06-18', '', '', '', 'Nursery 2', '', '', '', '2024-06-18 19:17:23', 1, 38, 'Benedita', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (37, 'Amarachi', 'Chinedu', 'amarachi.chinedu', 'fR1FdbLX', 'female', '2024-06-18', '', '', '', 'Nursery 2', '', '', '', '2024-06-18 19:18:57', 1, 39, 'Mary', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (38, 'Nneomannaya', 'Nwankpa', 'nneomannaya.nwankpa', 'shnu3ZTj', 'female', '2024-06-18', '', '', '', 'Nursery 2', '', '', '', '2024-06-18 19:20:16', 1, 40, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (39, 'Ugoeze', 'Chidi', 'ugoeze.chidi', 'GUTrgk0y', 'female', '2024-06-18', '', '', '', 'Nursery 2', '', '', '', '2024-06-18 19:21:03', 1, 41, 'Delight', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (40, 'Chikamso', 'Odimegwu', 'chikamso.odimegwu', 'jsePBrvn', 'male', '2024-06-18', '', '', '', 'Nursery 2', '', '', '', '2024-06-18 19:22:43', 1, 42, 'Daniel', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (41, 'Divine', 'Ndubueze ', 'divine.ndubueze', '11yCv6L0', 'female', '2024-06-18', '', '', '', 'Nursery 2', '', '', '', '2024-06-18 19:23:44', 1, 43, 'Chinaecherem', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (42, 'Future', 'Anosike', 'future.anosike', 'yo5676AI', 'male', '2024-06-18', '', '', '', 'Nursery 3', '', '', '', '2024-06-18 22:47:30', 1, 44, 'Junior', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (43, 'Daniel ', 'Asoegwu', 'daniel.asoegwu', 'acQWAhZ8', 'male', '2024-06-18', '', '', '', 'Nursery 3', '', '', '', '2024-06-18 22:48:02', 1, 45, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (44, 'Flourish ', 'Maduabuchi ', 'flourish.maduabuchi', 'MpIxURvj', 'female', '2024-06-18', '', '', '', 'Nursery 3', '', '', '', '2024-06-18 22:48:53', 1, 46, 'Chimamanda', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (46, 'Nice', 'Freedom ', 'nice.freedom', 'PaAuhG5r', 'female', '2024-06-18', '', '', '', 'Nursery 3', '', '', '', '2024-06-18 22:50:41', 1, 48, 'Chibuikem ', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (47, 'David', 'Chinenye ', 'david.chinenye', 'JrO0eKrr', 'male', '2024-06-18', '', '', '', 'Nursery 3', '', '', '', '2024-06-18 22:51:55', 1, 49, 'Chimnadinda', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (48, 'Victory', 'Gideon', 'victory.gideon', 'HoKNuO0M', 'male', '2024-06-18', '', '', '', 'Basic 1', '', '', '', '2024-06-18 22:55:27', 1, 50, 'Chibuikem', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (49, 'Callistus', 'Moses', 'callistus.moses', '1FPsg1yh', 'male', '2024-06-18', '', '', '', 'Basic 1', '', '', '', '2024-06-18 22:56:13', 1, 51, 'Ekeoma', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (50, 'Samuel ', 'Ime', 'samuel.ime', 'pcABbphG', 'male', '2024-06-18', '', '', '', 'Basic 1', '', '', '', '2024-06-18 22:56:40', 1, 52, 'Chidiebere', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (51, 'Winner', 'Chidi', 'winner.chidi', 'uSKYzatg', 'male', '2024-06-18', '', '', '', 'Basic 1', '', '', '', '2024-06-18 22:58:08', 1, 53, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (52, 'Miracle ', 'Ndubueze ', 'miracle.ndubueze', 'NzUCYjy1', 'female', '2024-06-18', '', '', '', 'Basic 1', '', '', '', '2024-06-18 22:59:01', 1, 54, 'Chizimdiri', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (53, 'Esther ', 'Nwankpa', 'esther.nwankpa', 'cNNufffU', 'female', '2024-06-18', '', '', '', 'Basic 1', '', '', '', '2024-06-18 22:59:55', 1, 55, 'Chiwenmeri', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (54, 'Prince', 'Nwankpa', 'prince.nwankpa', 'jw93DayE', 'male', '2024-06-19', '', '', '', 'Basic 1', '', '', '', '2024-06-18 23:00:35', 1, 56, 'Chizaram', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (55, 'Chinyere ', 'Emmanuel ', 'chinyere.emmanuel', 'suqz2114', 'female', '2024-06-19', '', '', '', 'Basic 2', '', '', '', '2024-06-18 23:01:55', 1, 57, 'Precious', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (56, 'Marvellous ', 'Maduabuchi', 'marvellous.maduabuchi', 'Cw3RWk81', 'male', '2024-06-19', '', '', '', 'Basic 2', '', '', '', '2024-06-18 23:02:37', 1, 58, 'Kamsi', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (57, 'Treasure ', 'Chidi', 'treasure.chidi', 'HYRwmXyI', 'female', '2024-06-19', '', '', '', 'Basic 2', '', '', '', '2024-06-18 23:03:37', 1, 59, 'Chinaecherem ', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (58, 'Believe ', 'Kanu', 'believe.kanu', 'uJAeRBz4', 'male', '2024-06-19', '', '', '', 'Basic 2', '', '', '', '2024-06-18 23:04:05', 1, 60, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (59, 'Amazing', 'Kanu', 'amazing.kanu', '8CL8fuW7', 'female', '2024-06-19', '', '', '', 'Basic 2', '', '', '', '2024-06-18 23:04:58', 1, 61, 'Amarachi ', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (60, 'Chukwuemeka', 'Nwaobia', 'chukwuemeka.nwaobia', '7TkZb4mo', 'male', '2024-06-19', '', '', '', 'Basic 2', '', '', '', '2024-06-18 23:06:07', 1, 62, 'Michael', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (61, 'Light', 'Chinyeaka', 'light.chinyeaka', 'PnuRAViN', 'male', '2024-06-19', '', '', '', 'Basic 3', '', '', '', '2024-06-18 23:07:51', 1, 63, 'Chizaram ', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (62, 'Chisom', 'Chinedu', 'chisom.chinedu', 'ayNeAE5W', 'female', '2024-06-19', '', '', '', 'Basic 3', '', '', '', '2024-06-18 23:08:45', 1, 64, 'Christabel', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (63, 'Esther ', 'Asoegwu ', 'esther.asoegwu', 'rSo13w3A', 'female', '2024-06-19', '', '', '', 'Basic 3', '', '', '', '2024-06-18 23:09:26', 1, 65, 'Kosisochukwu', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (64, 'Somotochukwu', 'Eze', 'somotochukwu.eze', 'wA4nN5vg', 'male', '2024-06-19', '', '', '', 'Basic 3', '', '', '', '2024-06-18 23:10:33', 1, 66, 'Destiny', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (65, 'Victoria ', 'Uwadiegwu ', 'victoria.uwadiegwu', 'f62Ura6v', 'female', '2012-02-23', '07069941822', '291 yellow avenue', 'Trader ', 'Basic 2', 'Imo state ', 'Ahiara  Ahiazu Mbaise ', 'Christianity', '2024-06-19 09:54:23', 1, 67, 'Chizitere ', 'Uwadiegwu chinwe ', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (66, 'Prevailer ', 'Ekene', 'prevailer.ekene', '3ovxrJuX', 'female', '2013-05-09', '08033463725', 'Alaukwu ', 'Pharmacy ', 'Basic 5', 'Imo state ', 'Ihioma orlu', 'Christianity', '2024-06-19 10:07:47', 1, 68, 'Chimnadindu', 'Ekene eboh', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (67, 'Beauty ', 'Ime ', 'beauty.ime', 'WV1j0y2A', 'female', '2011-11-24', '', '', 'Police Man ', 'Basic 5', 'Akwa ibom ', '', 'Christianity', '2024-06-19 10:17:18', 1, 69, 'Chidinma ', 'Ime  Emmanuel ', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (68, 'Chidiebube', 'Nwaobia ', 'chidiebube.nwaobia', 'L59GK6Ok', 'male', '2014-02-01', '07064672394', 'No 7 udezuka street ', 'Banker ', 'Basic 4', 'Imo state ', 'Abom mbaise', 'Christianity', '2024-06-19 10:42:12', 1, 70, 'Kingsley', 'Anosike Anulika Dominica', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (70, 'Oluchukwu ', 'Okoye ', 'oluchukwu.okoye', 'r1gFWmkc', 'female', '2012-12-12', '07034477956', 'No 33 Agalaba ', 'Trade', 'Basic 4', 'Anambra ', 'Nneofia', 'Christianity', '2024-06-19 10:51:08', 1, 72, 'Esther ', 'Ndubueze ', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (71, 'Olivia', 'Gideon', 'olivia.gideon', '6qMJTV4c', 'female', '2014-06-07', '', 'No  9 Umunwankwo street', 'Lecturing', 'Basic 4', 'Abia state ', 'Isiala Ngwa', 'Christianity', '2024-06-19 11:06:53', 1, 73, 'Somtochi ', 'Gideon Ngozi Sunday ', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (72, 'Prince Charles ', 'Asoegwu', 'charles.asoegwu', 'JF8w3xpv', 'male', '2012-08-26', '08037597170', 'No 271 Aba Owerri Road', 'Navy Man ', 'Basic 4', 'Anambra ', 'Nnewi ', 'Christianity', '2024-06-19 11:19:51', 1, 74, 'Ugochukwu ', 'Asoegwu Jeremiah ', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (73, 'Delight', 'Ezeribe', 'delight.ezeribe', 'o55mUwwr', 'female', '2012-08-06', '08038684734', 'No  4  MCC Road', 'Business woman ', 'Basic 4', 'Imo state ', 'Oru  East', 'Christianity', '2024-06-19 11:34:09', 1, 75, 'Ujunwa', 'Loveth Chidinma Ezeribe', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (74, 'Chimaobi', 'Uwadiegwu ', 'chimaobi.uwadiegwu', 'tW9kJgIs', 'male', '2011-03-27', '+9715541617', '291 yellow avenue', 'Business Man', 'Basic 6', 'Imo state ', 'Ahiara  Ahiazu Mbaise ', 'Christianity', '2024-06-19 11:47:12', 1, 76, 'David', 'Uwadiegwu Chinemerem', 0);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (76, 'Ime ', 'Goodluck ', 'ime.goodluck', 'yjLJD6YA', 'male', '2008-12-03', '07065511818', 'Osisioma Barack ', 'Police woman', 'JSS 1', 'Akwa Ibom ', '', 'Christianity', '2024-06-19 12:09:27', 1, 78, 'Chiweotito ', 'Lynda ime ', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (78, 'Precious ', 'Ekene', 'precious.ekene', 'HAja5XIO', 'female', '2011-08-01', '08033463725', 'Elebele ', 'Pharmacy ', 'JSS 1', 'Imo state ', 'Ihioma orlu', 'Christianity', '2024-06-25 14:12:11', 1, 87, 'Adaeze', 'Ekene eboh', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (81, 'Destiny', 'Chiemela ', 'destiny.chiemela', 'nDnhTuxT', 'female', '2012-07-30', '07031885006', 'Uratta', 'Painter ', 'Basic 5', 'Abia', 'Isiala Ngwa south', 'Christianity', '2024-06-27 11:58:39', 0, 91, 'Chigozirim', 'Mr Chiemela George ', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (82, 'Chijindu', 'Williams', 'chijindu.williams', 'MTuDu2R2', 'male', NULL, '', '', '', 'Nursery 3', '', '', '', '2024-06-27 12:12:02', 1, 92, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (83, 'Chimamanda', 'Nwaobia', 'chimamanda.nwaobia', 'CNSnhnA3', 'female', '2017-11-10', '07064672394', 'No 7 udezuka street ', 'Banker ', 'Nursery 3', 'Imo state ', 'Abom mbaise', 'Christianity', '2024-06-27 12:17:19', 1, 93, 'Daniela', 'Anulika Anosike Dominica', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (84, 'Glory ', 'Uwadiegwu ', 'glory.uwadiegwu', 'Jti75keD', 'female', '2007-12-29', 'O7o69941822', 'Yellow avenue ', 'Business woman ', 'JSS 1', 'Imo state ', 'Mbaise ', 'Christianity ', '2024-07-02 10:37:01', 1, 94, 'Ogochukwu ', 'Chinwe ', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (85, 'Success', 'Israel', 'success.israel', 'GujfiUGx', 'male', NULL, '', '', '', 'Basic 1', '', '', '', '2024-07-15 10:32:12', 1, 95, '', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (86, 'Sochima', 'Samuel ', 'sochima.samuel', 'vg4qGxzY', 'female', NULL, '', '', '', 'Creche', '', '', '', '2024-07-26 07:33:22', 1, 96, 'Kindness', '', NULL);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (87, 'Joshua', 'Iheanyi', 'joshua.iheanyi', 'eqMQlhmD', 'male', NULL, '', '', '', NULL, '', '', '', '2024-11-10 11:19:27', 0, 98, '', '', 0);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (88, 'Stanley', 'Alexander', 'stanley.alexander', 'RftVfcas', 'male', NULL, '', '', '', NULL, '', '', '', '2024-11-10 11:22:12', 0, 99, '', '', 0);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (89, 'Excel', 'Joseph', 'excel.joseph', 'LgE17Mqy', 'male', NULL, '', '', '', NULL, '', '', '', '2024-11-12 15:42:27', 0, 100, '', '', 0);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (90, 'Royalty', 'Anosike', 'royalty.anosike', '7sVnGKJC', 'male', NULL, '', '', '', NULL, '', '', '', '2024-11-12 15:42:54', 0, 101, '', '', 0);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (91, 'Wisdom', 'Augustine', 'wisdom.augustine', 'XpFZ1c3q', 'male', NULL, '', '', '', NULL, '', '', '', '2024-11-12 15:43:21', 0, 102, '', '', 0);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (92, 'Miracle', 'John', 'miracle.john', 'QaQ3dgar', 'male', NULL, '', '', '', NULL, '', '', '', '2024-11-12 15:43:54', 0, 103, '', '', 0);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (93, 'Onyinyechi', 'Augustine', 'onyinyechi.augustine', 'ajpwSmN2', 'female', NULL, '', '', '', NULL, '', '', '', '2024-11-12 15:44:38', 0, 104, '', '', 0);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (94, 'Emmanuel', 'Joseph', 'emmanuel.joseph', 'IxG9dLJl', 'male', NULL, '', '', '', NULL, '', '', '', '2024-11-12 15:45:09', 0, 105, '', '', 0);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (95, 'Chijindu', 'Sunday', 'chijindu.sunday', 'ye87ZdZr', 'female', NULL, '', '', '', NULL, '', '', '', '2024-11-12 15:53:10', 0, 106, '', '', 0);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (96, 'Great', 'Augustine', 'great.augustine', 'FzCi6XNL', 'male', NULL, '', '', '', NULL, '', '', '', '2024-11-12 15:54:13', 0, 107, '', '', 0);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (97, 'David', 'Onyenwe', 'david.onyenwe', '1Pauc491', 'male', NULL, '', '', '', NULL, '', '', '', '2024-11-12 15:56:08', 0, 108, '', '', 0);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (98, 'Joyful', 'Praise', 'joyful.praise', 'LOgrhKYV', 'female', NULL, '', '', '', NULL, '', '', '', '2024-11-12 15:56:36', 0, 109, '', '', 0);
INSERT INTO student (id, first_name, last_name, username, password, gender, date_of_birth, parent_phone_number, address, parent_occupation, previous_class, state_of_origin, local_government_area, religion, date_registered, approved, user_id, middle_name, parent_name, has_paid_fee) VALUES (99, 'Munachimso', 'David', 'munachimso.david', 'sAbvRIuq', 'female', NULL, '', '', '', NULL, '', '', '', '2024-11-12 15:58:40', 0, 110, '', '', 0);

