"""Modify models

Revision ID: 36c85aa11683
Revises: 7ba49d86a77d
Create Date: 2024-06-19 01:24:05.102970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36c85aa11683'
down_revision = '7ba49d86a77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('term',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('session',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('grade',
               existing_type=mysql.VARCHAR(length=2),
               type_=sa.String(length=5),
               nullable=True)
        batch_op.alter_column('remark',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('parent_name', sa.String(length=70), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('parent_name')
        batch_op.drop_column('middle_name')

    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('remark',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('grade',
               existing_type=sa.String(length=5),
               type_=mysql.VARCHAR(length=2),
               nullable=False)
        batch_op.alter_column('session',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.alter_column('term',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###
