"""Modify models

Revision ID: 6ae6c76fced5
Revises: e1e54342c5e2
Create Date: 2024-06-14 01:53:06.325494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ae6c76fced5'
down_revision = 'e1e54342c5e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=20), nullable=False),
    sa.Column('session', sa.String(length=20), nullable=False),
    sa.Column('class_assessment', sa.Integer(), nullable=True),
    sa.Column('summative_test', sa.Integer(), nullable=True),
    sa.Column('exam', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('remark', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('current_term')
        batch_op.drop_column('current_session')

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_index('name')
        batch_op.create_unique_constraint('_name_section_uc', ['name', 'section'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint('_name_section_uc', type_='unique')
        batch_op.create_index('name', ['name'], unique=True)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_session', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('current_term', mysql.VARCHAR(length=10), nullable=True))

    op.drop_table('result')
    # ### end Alembic commands ###
