"""Modify models

Revision ID: 7ba49d86a77d
Revises: 625ca2d08d05
Create Date: 2024-06-14 05:52:48.116008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ba49d86a77d'
down_revision = '625ca2d08d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.create_table('score',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('class_assessment', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('summative_test', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exam', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('term', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('session', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('grade', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('remark', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='score_ibfk_1'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name='score_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
