"""Modify models

Revision ID: c3b907822902
Revises: 6ae6c76fced5
Create Date: 2024-06-14 02:23:05.093519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3b907822902'
down_revision = '6ae6c76fced5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.String(length=2),
               nullable=False)
        batch_op.alter_column('remark',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('term')
        batch_op.drop_column('session')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('term', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('remark',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('grade',
               existing_type=sa.String(length=2),
               type_=mysql.VARCHAR(length=5),
               nullable=True)

    # ### end Alembic commands ###
