"""Add term and session to student model

Revision ID: cc26a7dabac0
Revises: 
Create Date: 2024-06-09 19:05:51.520087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc26a7dabac0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_session', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('current_term', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('current_term')
        batch_op.drop_column('current_session')

    # ### end Alembic commands ###
